SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE proc [dbo].[Proc_Trans_Net_Datos]
@RucE nvarchar(11)
AS
exec dbo.Proc_Transf_Conta_Net_Vinculo @RucE
exec dbo.Proc_Transf_Conta_Net_TipDocES @RucE
exec dbo.Proc_Transf_Conta_Net_Serie @RucE
exec dbo.Proc_Transf_Conta_Net_Producto @RucE
exec dbo.Proc_Transf_Conta_Net_Transportista @RucE
exec dbo.Proc_Transf_Conta_Net_Marca @RucE
exec dbo.Proc_Transf_Conta_Net_ComisionGrupProd @RucE
exec dbo.Proc_Transf_Conta_Net_ComisionGrupVdr @RucE
exec dbo.Proc_Transf_Conta_Net_ComisionGrupCte @RucE
exec dbo.Proc_Transf_Conta_Net_CfgAutorizacion @RucE
exec dbo.Proc_Transf_Conta_Net_CfgNivelAut @Ruce
exec dbo.Proc_Transf_Conta_Net_Empresa @RucE
exec dbo.Proc_Transf_Conta_Net_MtvoIngSal @RucE
exec dbo.Proc_Transf_Conta_Net_Cliente2 @RucE
exec dbo.Proc_Transf_Conta_Net_Campo @RucE
exec dbo.Proc_Transf_Conta_Net_CfgEnvCorreo @RucE
exec dbo.Proc_Transf_Conta_Net_CotizacionFormato @RucE
exec dbo.Proc_Transf_Conta_Net_GuiaRemision @RucE
exec dbo.Proc_Transf_Conta_Net_Almacen @RucE
exec dbo.Proc_Transf_Conta_Net_Periodo @RucE
exec dbo.Proc_Transf_Conta_Net_CarteraProd @RucE
exec dbo.Proc_Transf_Conta_Net_CCostos @RucE
exec dbo.Proc_Transf_Conta_Net_CCSub @RucE
exec dbo.Proc_Transf_Conta_Net_CCSubSub @RucE
exec dbo.Proc_Transf_Conta_Net_Area @RucE
exec dbo.Proc_Transf_Conta_Net_SolicitudReq @RucE
exec dbo.Proc_Transf_Conta_Net_SolicitudCom @RucE
exec dbo.Proc_Transf_Conta_Net_OrdCompra @RucE
exec dbo.Proc_Transf_Conta_Net_Vendedor2 @RucE
exec dbo.Proc_Transf_Conta_Net_Auxiliar @RucE
exec dbo.Proc_Transf_Conta_Net_Vendedor @RucE
exec dbo.Proc_Transf_Conta_Net_Cliente @RucE
exec dbo.Proc_Transf_Conta_Net_Cotizacion @RucE
exec dbo.Proc_Transf_Conta_Net_OrdPedido @RucE
exec dbo.Proc_Transf_Conta_Net_Venta @RucE
exec dbo.Proc_Transf_Conta_Net_Proveedor @RucE
exec dbo.Proc_Transf_Conta_Net_Proveedor2 @RucE
exec dbo.Proc_Transf_Conta_Net_GrupoSrv @RucE
exec dbo.Proc_Transf_Conta_Net_Servicio @RucE
exec dbo.Proc_Transf_Conta_Net_Servicio2 @RucE
exec dbo.Proc_Transf_Conta_Net_Clase @RucE
exec dbo.Proc_Transf_Conta_Net_ClaseSub @RucE
exec dbo.Proc_Transf_Conta_Net_ClaseSubSub @RucE
exec dbo.Proc_Transf_Conta_Net_Producto2 @RucE
exec dbo.Proc_Transf_Conta_Net_Serial @RucE
exec dbo.Proc_Transf_Conta_Net_ConceptosDetrac @RucE
exec dbo.Proc_Transf_Conta_Net_Prod_UM @RucE
exec dbo.Proc_Transf_Conta_Net_ServProv @RucE
exec dbo.Proc_Transf_Conta_Net_ProdProv @RucE
exec dbo.Proc_Transf_Conta_Net_Precio @RucE
exec dbo.Proc_Transf_Conta_Net_CotizacionDet @RucE
exec dbo.Proc_Transf_Conta_Net_Compra @RucE
exec dbo.Proc_Transf_Conta_Net_Formula @RucE
exec dbo.Proc_Transf_Conta_Net_OrdFabricacion @RucE
exec dbo.Proc_Transf_Conta_Net_CptoCosto @RucE
exec dbo.Proc_Transf_Conta_Net_CptoCostoOF @RucE
exec dbo.Proc_Transf_Conta_Net_VoucherRM @RucE
exec dbo.Proc_Transf_Conta_Net_VoucherDR @RucE
exec dbo.Proc_Transf_Conta_Net_Voucher @RucE
exec dbo.Proc_Transf_Conta_Net_VentaRM @RucE
exec dbo.Proc_Transf_Conta_Net_VentaDet @RucE
exec dbo.Proc_Transf_Conta_Net_VentaCfg @RucE
exec dbo.Proc_Transf_Conta_Net_SolicitudReqDet @RucE
exec dbo.Proc_Transf_Conta_Net_SolicitudComDet @RucE
exec dbo.Proc_Transf_Conta_Net_ServProvPrecio @RucE
exec dbo.Proc_Transf_Conta_Net_SeriesXArea @RucE
exec dbo.Proc_Transf_Conta_Net_SerialMov @RucE
exec dbo.Proc_Transf_Conta_Net_SCxProv @RucE
exec dbo.Proc_Transf_Conta_Net_ProdSustituto @RucE
exec dbo.Proc_Transf_Conta_Net_ProdProvPrecio @RucE
exec dbo.Proc_Transf_Conta_Net_ProdCombo @RucE
exec dbo.Proc_Transf_Conta_Net_Presupuesto @RucE
exec dbo.Proc_Transf_Conta_Net_PresupFC @RucE
exec dbo.Proc_Transf_Conta_Net_PresupCpto @RucE
exec dbo.Proc_Transf_Conta_Net_PrecioSrv @RucE
exec dbo.Proc_Transf_Conta_Net_PrecioHist @RucE
exec dbo.Proc_Transf_Conta_Net_PrdoCons @RucE
exec dbo.Proc_Transf_Conta_Net_PlanCtasDef @RucE
exec dbo.Proc_Transf_Conta_Net_PlanCtas @RucE
exec dbo.Proc_Transf_Conta_Net_PersonaRef @RucE
exec dbo.Proc_Transf_Conta_Net_OrdPedidoDet @RucE
exec dbo.Proc_Transf_Conta_Net_OrdCompraDet @RucE
exec dbo.Proc_Transf_Conta_Net_Numeracion @RucE
exec dbo.Proc_Transf_Conta_Net_Inventario @RucE
exec dbo.Proc_Transf_Conta_Net_GuiaXVenta @RucE
exec dbo.Proc_Transf_Conta_Net_GuiaXCompra @RucE
exec dbo.Proc_Transf_Conta_Net_GuiaRemisionDet @RucE
exec dbo.Proc_Transf_Conta_Net_GRPtoLlegada @RucE
exec dbo.Proc_Transf_Conta_Net_GeneralRM @RucE
exec dbo.Proc_Transf_Conta_Net_FrmlaOF @RucE
exec dbo.Proc_Transf_Conta_Net_FormulaDet @RucE
exec dbo.Proc_Transf_Conta_Net_EnvEmbOF @RucE
exec dbo.Proc_Transf_Conta_Net_DocsVta @RucE
exec dbo.Proc_Transf_Conta_Net_DocsVou @RucE
exec dbo.Proc_Transf_Conta_Net_DocsCom @RucE
exec dbo.Proc_Transf_Conta_Net_DirecTrans @RucE
exec dbo.Proc_Transf_Conta_Net_DirecEnt @RucE
exec dbo.Proc_Transf_Conta_Net_CptoDetxProv @RucE
exec dbo.Proc_Transf_Conta_Net_CptoCostoOFDoc @RucE
exec dbo.Proc_Transf_Conta_Net_CotizacionProdDet @RucE
exec dbo.Proc_Transf_Conta_Net_Contacto @RucE
exec dbo.Proc_Transf_Conta_Net_ConceptoDetracHist @RucE
exec dbo.Proc_Transf_Conta_Net_CompraDet @RucE
exec dbo.Proc_Transf_Conta_Net_ComisionConfig @RucE
exec dbo.Proc_Transf_Conta_Net_Cobro @RucE
exec dbo.Proc_Transf_Conta_Net_CfgGeneral @RucE
exec dbo.Proc_Transf_Conta_Net_CfgEnvSC @RucE
exec dbo.Proc_Transf_Conta_Net_CfgEnvCot @RucE
exec dbo.Proc_Transf_Conta_Net_CfgEmpsBase @RucE
exec dbo.Proc_Transf_Conta_Net_CfgCampos @RucE
exec dbo.Proc_Transf_Conta_Net_CarteraProdDet_S @RucE
exec dbo.Proc_Transf_Conta_Net_CarteraProdDet_P @RucE
exec dbo.Proc_Transf_Conta_Net_CampoV @RucE
exec dbo.Proc_Transf_Conta_Net_Banco @RucE
exec dbo.Proc_Transf_Conta_Net_AuxiliarRM @RucE
exec dbo.Proc_Transf_Conta_Net_AutSR @RucE
exec dbo.Proc_Transf_Conta_Net_AutSC @RucE
exec dbo.Proc_Transf_Conta_Net_AutOP @RucE
exec dbo.Proc_Transf_Conta_Net_AutOF @RucE
exec dbo.Proc_Transf_Conta_Net_AutOC @RucE
exec dbo.Proc_Transf_Conta_Net_AutCot @RucE
exec dbo.Proc_Transf_Conta_Net_Asiento @RucE
exec dbo.Proc_Transf_Conta_Net_Articulo @RucE
exec dbo.Proc_Transf_Conta_Net_AmarreRpt @RucE
exec dbo.Proc_Transf_Conta_Net_AmarreCta @RucE
exec dbo.Proc_Transf_Conta_Net_AlmacenStock @RucE
exec dbo.Proc_Transf_Conta_Net_AccesoE @RucE
--PP/FL : 12/05/2011 <creacion de sp>

GO
