SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[Vta_NroDocValida]
@RUCE NVARCHAR(11), 
@CD_SR NVARCHAR(4),
@NRODOC NVARCHAR(15),
@MSJ VARCHAR(100) OUTPUT
--WITH ENCRYPTION
AS

IF(@NRODOC='' OR @NRODOC IS NULL)
BEGIN	SET @MSJ='NO INGRESO NUMERO DE DOCUMENTO'
	PRINT @MSJ
	RETURN
END


declare @NroSre nvarchar(5), @Cd_TD nvarchar(2)
Select @Cd_TD = Cd_TD, @NroSre = NroSerie from Serie where RucE = @RucE and Cd_Sr=@Cd_Sr



--IF EXISTS (SELECT NRODOC FROM VENTA WHERE RUCE=@RUCE AND CD_SR=@CD_SR AND NRODOC=@NRODOC)
IF EXISTS (SELECT NRODOC FROM VENTA WHERE RUCE=@RUCE AND Cd_TD=@Cd_TD and NroSre = @NroSre AND NRODOC=@NRODOC)
BEGIN	SET @MSJ='NUMERO DE DOCUMENTO YA HA SIDO USADO'
	PRINT @MSJ
	RETURN
END


DECLARE @RI INT, @RS INT, @ND INT, @VALIDO BIT
SET @ND = CONVERT(INT,@NRODOC)
SET @VALIDO=0


DECLARE CUR_NUM CURSOR FOR SELECT DESDE, HASTA FROM NUMERACION WHERE RUCE=@RUCE AND CD_SR=@CD_SR
OPEN CUR_NUM
       FETCH CUR_NUM INTO @RI, @RS
       WHILE(@@FETCH_STATUS=0) 
       BEGIN
	    --PRINT @ND PRINT @RI PRINT @RS
	    IF(@ND>=@RI AND @ND<=@RS)
	    BEGIN
		SET @VALIDO=1
		BREAK
	    END
		
	    FETCH CUR_NUM INTO @RI, @RS
       END
CLOSE CUR_NUM
DEALLOCATE CUR_NUM

IF(@VALIDO=0)
   SET @MSJ='NRO DE DOCUMENTO NO ESTA DENTRO DEL RANGO AUTORIZADO'
PRINT @MSJ


--PV: Vie 12/11/2010

GO
