SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[VTA_NRODOCGENERA_GUIA]
@RUCE NVARCHAR(11), 
@CD_SR NVARCHAR(4),
@NROGR NVARCHAR(7)OUTPUT,
--@CD_NUM NVARCHAR(4)OUTPUT,
@MSJ VARCHAR(100) OUTPUT
--WITH ENCRYPTION
AS
DECLARE @N INT, @C NVARCHAR(7)
--SET @ND = CONVERT(INT,@NRODOC)

IF((SELECT COUNT(CD_NUM) FROM NUMERACION WHERE CD_SR=@CD_SR)<=0)
BEGIN
     SET @MSJ = 'SERIE NO POSEE NIGUNA NUMERACION'
     PRINT @MSJ
     RETURN	
END

declare @NroSre nvarchar(5), @Cd_TD nvarchar(2)
Select @Cd_TD = Cd_TD, @NroSre = NroSerie from Serie where RucE = @RucE and Cd_Sr=@Cd_Sr



--SELECT @N = COUNT(NRODOC) FROM VENTA WHERE RUCE=@RUCE AND CD_SR=@CD_SR
SELECT @N = COUNT(NROGR) FROM GUIAREMISION WHERE RUCE=@RUCE AND Cd_TD=@Cd_TD and NroSre = @NroSre
PRINT 'NRO GUIA REMISION: ' PRINT @N

IF @N=0
BEGIN
   SET @N= (SELECT MIN(DESDE) FROM NUMERACION WHERE RUCE=@RUCE AND CD_SR=@CD_SR )
   PRINT 'MIN DESDE NUMERACION: ' PRINT @N
   SET @NROGR = RIGHT('0000000'+LTRIM(STR(@N)), 7)
--   SET @CD_NUM = (SELECT CD_NUM FROM NUMERACION WHERE RUCE=@RUCE AND CD_SR=@CD_SR AND DESDE=@N )
END
ELSE
BEGIN
   --SELECT @C=MAX(CONVERT(INT,NRODOC)) FROM VENTA WHERE RUCE=@RUCE AND CD_SR=@CD_SR
   SELECT @C=MAX(CONVERT(INT,NROGR)) FROM GUIAREMISION WHERE RUCE=@RUCE AND Cd_TD=@Cd_TD and NroSre = @NroSre and IC_ES='S'
   IF(@C is null) set @C=0
-- SET @C= RIGHT(@C,2)  --> SOLO ES NECESARIO SI LLEVA UNA LETRA ADELANTE
   PRINT 'MAX NRODOC GUIA REMISION: ' PRINT @C
   SET @N =CONVERT(INT, @C)+1
   ----ALGORITMO PAVLOV-----
   IF EXISTS(SELECT * FROM NUMERACION WHERE RUCE=@RUCE AND CD_SR=@CD_SR AND DESDE<=@N AND HASTA>=@N  )
     BEGIN
	SET @NROGR = RIGHT('0000000'+LTRIM(STR(@N)), 7)
	--PRINT @NROGR
--	SET @CD_NUM = (SELECT CD_NUM FROM NUMERACION WHERE RUCE=@RUCE AND CD_SR=@CD_SR AND DESDE<=@N AND HASTA>=@N  )
	--RETURN
     END
   ELSE 
     BEGIN
print @N
	SET @N =( SELECT min(DESDE) FROM NUMERACION WHERE RUCE=@RUCE AND CD_SR=@CD_SR AND DESDE>=@N)
	IF(@N=NULL OR @N IS NULL)
	   SET @MSJ = 'NO SE PUDO GENERAR UN NRO DE DOCUMENTO VALIDO. REVISAR MANTENIMINETO DE NUMERACION'
	ELSE
	BEGIN SET @NROGR = RIGHT('0000000'+LTRIM(STR(@N)), 7)
--	      SET @CD_NUM = (SELECT CD_NUM FROM NUMERACION WHERE RUCE=@RUCE AND CD_SR=@CD_SR AND DESDE=@N )
	END
     END   

END
--PRINT @MSJ
PRINT @NROGR

-- exec VTA_NRODOCGENERA_GUIA '20518362357','S006','',''
GO
