SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[spTraerTodasTablaClassCreator]

AS

SELECT
	SYS.OBJECTS.OBJECT_ID AS ID_TABLA,
	SYS.OBJECTS.NAME AS NOM_TABLA
FROM	SYS.OBJECTS 
WHERE	SYS.OBJECTS.TYPE = 'U' 

ORDER BY NOM_TABLA

GO
