CREATE TABLE [user321].[Ventas$]
(
[RucE] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[Cd_Vta] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[Eje] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[Prdo] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[RegCtb] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[FecMov] [smalldatetime] NULL,
[Cd_FPC] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[FecCbr] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[Cd_TD] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[NroDoc] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[Cd_Sr_NO] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[Cd_Num_NO] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[FecED] [smalldatetime] NULL,
[FecVD] [smalldatetime] NULL,
[Cd_Cte_NO] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[Cd_Vdr_NO] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[Cd_Area] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[Cd_MR] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[Obs] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[Valor] [float] NULL,
[TotDsctoP] [float] NULL,
[TotDsctoI] [float] NULL,
[ValorNeto] [float] NULL,
[BaseSinDsctoF] [float] NULL,
[DsctoFnz_P] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[DsctoFnz_I] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[Cd_IAV_DF] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[INF_Neto] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[EXO_Neto] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[EXPO_Neto] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[BIM_Neto] [float] NULL,
[IGV] [float] NULL,
[Total] [float] NULL,
[Percep] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[Cd_Mda] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[CamMda] [float] NULL,
[FecReg] [smalldatetime] NULL,
[FecMdf] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[UsuCrea] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[UsuModf] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[IB_Anulado] [bit] NOT NULL,
[IB_Cbdo] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[DR_CdVta] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[DR_FecED] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[DR_CdTD] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[DR_NSre] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[DR_NDoc] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[CA01] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[CA02] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[CA03] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[CA04] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[CA05] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[CA06] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[CA07] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[CA08] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[CA09] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[CA10] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[CA11] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[CA12] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[CA13] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[CA14] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[CA15] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[Cd_OP] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[NroOP] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[Cd_CC] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[Cd_SC] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[Cd_SS] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[NroSre] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[Cd_MIS] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[Cd_Clt] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL,
[Cd_Vdr] [nvarchar] (255) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
